config/routes.rb
AddonTest::Application.routes.draw do
  root :to => 'welcome#index'

  post 'todos', to: "welcome#create", as: :new_todo
  delete 'todos/:id', to: "welcome#destroy", as: :delete_todo
  get 'todos/:id/edit', to: "welcome#edit", as: :edit_todo
  put 'todos/:id/', to: "welcome#update", as: :update_todo
  get 'noaddon', to: "welcome#no_addon", as: :no_addon

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def addon_api
    @addon_api ||= AddonApi.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :has_addon, except: :no_addon

  def index
    @todos = addon_api.index
  end

  def edit
    @todo = addon_api.show(params[:id])
  end

  def create
    addon_api.create(params[:text]) 
    redirect_to action: :index
  end

  def destroy
    addon_api.destroy(params[:id]) 
    redirect_to action: :index
  end

  def update
    addon_api.update(params[:id], params[:text]) 
    redirect_to action: :index
  end

  def no_addon
    render text: "Looks like you still havn't installed the addon into your app. please install it and then come back to this page"
  end

  protected

  def has_addon
    if ENV['TODOSADDON_ACCESS_TOKEN'].nil? or ENV['TODOSADDON_URL'].nil?
      redirect_to no_addon_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddonTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/edit.html.erb
<%= form_tag update_todo_path, method: "POST" %>
<%= hidden_field_tag :_method, "put" %>
<%= text_field_tag :text, @todo['text'] %>
<%= submit_tag :update, %>

<%=link_to "Back to Main", root_path %>

app/views/welcome/index.html.erb
<p>Hi This is a page to test the heroku addon</p>


<p>Here are the todos fetched from the addon</p>


<%= form_tag new_todo_path, method: "POST" %>
<%= text_field_tag :text, "", placeholder: "enter todo text here" %>
<%= submit_tag :create_new, %>

<br />

<%- @todos.each do |todo| %>
<p>
<%= "#{todo['id']} - #{todo['text']}" %>
<%= link_to "delete", delete_todo_path(id: todo['id']), method: :delete, confirm: "are you sure?" %>
<%= link_to "edit", edit_todo_path(id: todo['id']) %>
</p>
<%- end %>